#!/bin/bash

# Update package list
apt-get update

# Install Redis
apt-get -y install redis-server

# Install Redis library for Python
pip3 install redis

# Configure Redis to accept connections from localhost only
sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf

# Restart Redis service to apply changes
service redis-server restart
